### ISSUE TITLE
[BUG] Overrides other pages on update

### ISSUE THREAD

**Issue by jslay88** [StreamController/Weather#2]
I have multiple pages, but only 1 page with the Weather plugin added to a button.

When the wx update happens and I am on a different page than the one with the Weather plugin button, it will override that page's button with the Weather plugin button image and label, but not the actions.

**Comment by Core447** [comment]
Thanks for reporting this! I haven't been able to reproduce this yet, but I'll try a few more scenarios tomorrow. Are you using the Flatpak?

**Comment by jslay88** [comment]
Flatpak

Here showing a normal button that is used to change pages, with the image and label replaced by the WX update.

![image](https://github.com/StreamController/Weather/assets/6158929/9cc2b88c-3013-4004-a00f-af3272f18808)

**Comment by Core447** [comment]
I could reproduce this issue on the Flathub version, but not on the head of main. Seams like this has already been fixed by some other patch. Let's keep this open and check again after the next release.

**Comment by Core447** [comment]
As a workaround, you can set the number of cached pages to 0 in the preferences.

**Comment by Core447** [comment]
Is this still an issue for you?

**Comment by jslay88** [comment]
Seems to be fine now with 1.5.0
