### ISSUE TITLE
Keeps breaking

### ISSUE THREAD

**Issue by jpSimkins** [StreamController/Weather#3]
For some reason, this works for a day then will just break. It will show a triangle with an ! inside it. Nothing appears to be wrong but it just breaks.

I have been deleting it then re-adding it but today, even after readding it, it still won't work.

**Comment by Core447** [comment]
Very weird, I don't have this... Are the coordinates still present in the action configuration screen after this has happened, or do they get removed?

**Comment by jpSimkins** [comment]
Well, I reinstalled my OS and now it is working. Perhaps some bad update along the way. Either way, working now so closing this out. Thanks for your response!
